name: preprocess
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - scikit-learn
  - imbalanced-learn
  - hydra-core
  - omegaconf
  - python-dotenv
  - pyyaml
  - matplotlib
  - seaborn
  - pip
  - pip:
      - wandb
      - mlflow-skinny 