name: data_validation
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - hydra-core
  - omegaconf
  - python-dotenv
  - pyyaml
  - pip
  - pip:
      - wandb
      - mlflow-skinny 